In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [12]:
df = pd.read_csv('/content/hiring (1).csv')

df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
!pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=ff9c5ea52090146b646a14fe77040cc4e975e9d936ee8a4b65b304d8c7fec7c1
  Stored in directory: /root/.cache/pip/wheels/5b/79/fb/d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [14]:
from word2number import w2n

In [15]:
df['experience'] = df['experience'].fillna('zero')

In [16]:
df['experience'] = df['experience'].apply(w2n.word_to_num)

df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [18]:
df['experience'] = df['experience'].astype(str)

df['experience'] = df['experience'].apply(w2n.word_to_num)

df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [25]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(
    df['test_score(out of 10)'].median()
)

df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [26]:
X = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]

In [27]:
y = df['salary($)']

In [28]:
reg = linear_model.LinearRegression()

In [29]:
reg.fit(X, y)

LinearRegression()

In [31]:
import pandas as pd

sample = pd.DataFrame({
    'experience': [2],
    'test_score(out of 10)': [9],
    'interview_score(out of 10)': [6]
})

reg.predict(sample)

array([53205.96797671])